spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///LOL
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081
  servlet:
    context-path: /

file:
  dir: 'E:\Project\SpringTest\src\files\'
